### ISSUE TITLE
API-update

### ISSUE THREAD

**Issue by Photon-GitHub** [5zig/The-5zig-Mod-Server-Api#1]
Hello,
would it be possible to update this API ?
I listen to the channel "5ZIG" as it is done in this plugin, but I do not get a message from the client, thus I think that the api is outdated.
I would like to see this plugin up-to-date once again.
Moreover I would like to ask if the old possibility of controlling the features of a client with the bits of a byte is still valid; if the answer is yes, please update this page as well, otherwise please delete it.
Thanks in advance
~Photon

**Comment by 5zig** [comment]
The newest version of the API is available from here: https://github.com/5zig/The-5zig-Mod-API-2.0.
If you are looking for a way to disable some settings of the mod, check out https://gist.github.com/5zig/35e0854504edda418f4b
